insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (1, 'Document Drafting', 394);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (2, 'Chromatography', 334);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (3, 'CVIS', 220);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (4, 'Bash', 493);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (5, 'ISO 9000', 662);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (6, 'Professional Liability', 955);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (7, 'Failure Analysis', 3);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (8, 'Yard Management', 429);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (9, 'Object Oriented Modeling', 889);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (10, 'NCAA Compliance', 14);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (11, 'Cost Accounting', 590);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (12, 'WYSIWYG Layout Tools', 944);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (13, 'Bartending', 403);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (14, 'Avid', 385);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (15, 'Certified EKG Technician', 565);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (16, 'VMware Workstation', 359);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (17, 'DVB-S', 948);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (18, 'Ductwork', 893);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (19, 'Motivational Interviewing', 242);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (20, 'DVB-RCS', 181);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (21, 'Unreal Editor', 767);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (22, 'OMB A-123', 34);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (23, 'iPod', 347);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (24, 'NSE', 180);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (25, 'Eze Castle', 295);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (26, 'Jive SBS', 495);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (27, 'Eplan', 959);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (28, 'iLife', 819);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (29, 'Substance Abuse Prevention', 650);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (30, 'Gift Tax', 317);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (31, 'Social Media Blogging', 548);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (32, 'JiBX', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (33, 'Stakeholder Management', 826);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (34, 'Style Guides', 271);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (35, 'ESL', 950);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (36, 'International Trade', 131);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (37, 'Warehouse Management', 521);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (38, 'Oil &amp; Gas Services', 393);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (39, 'AAAHC', 97);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (40, 'Utility Construction', 457);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (41, 'DPM', 822);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (42, 'Labor Relations', 475);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (43, 'Aquariums', 786);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (44, 'Global Strategy', 281);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (45, 'ISO 27001', 588);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (46, 'Lead Generation', 636);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (47, 'Sqoop', 875);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (48, 'Electricity', 440);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (49, 'High Availability', 683);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (50, 'Vectorworks', 167);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (51, 'Construction Safety', 808);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (52, 'sFlow', 583);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (53, 'RCSA', 339);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (54, 'Project Portfolio Management', 264);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (55, 'IGRP', 440);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (56, 'Sales', 879);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (57, 'JVM', 773);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (58, 'GHS', 672);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (59, 'Kinetics', 236);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (60, 'New Hire Orientations', 433);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (61, 'Lucene', 58);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (62, 'MDA', 761);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (63, 'Jitterbit', 888);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (64, 'ION Marketview', 953);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (65, 'WebSphere Application Server', 786);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (66, 'Food Safety', 581);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (67, 'CSCP', 110);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (68, 'SEP IRA', 15);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (69, 'JVM', 304);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (70, 'Etching', 959);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (71, 'Patient Safety', 432);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (72, 'TSS', 6);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (73, 'UART', 66);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (74, 'cDNA', 318);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (75, 'Knee Pain', 842);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (76, 'Sap Fm', 506);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (77, 'BSI Tax Factory', 206);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (78, 'Zymography', 409);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (79, 'Flight Training', 316);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (80, 'HBSS', 130);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (81, 'AOI', 534);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (82, 'GIS Modeling', 308);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (83, 'iOS Design', 265);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (84, 'Dbx', 65);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (85, 'Geophysics', 752);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (86, 'Twitter API', 24);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (87, 'NSS', 624);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (88, 'Database Marketing', 371);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (89, 'TPNS', 436);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (90, 'VNA', 833);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (91, 'DDNS', 574);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (92, 'MHP', 310);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (93, 'RRDTool', 196);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (94, 'UFC', 552);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (95, 'DSLR', 972);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (96, 'Business Ethics', 296);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (97, 'CWTS', 921);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (98, 'GNU tools', 93);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (99, 'Grassroots', 260);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (100, 'Ships', 194);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (101, 'Aquaculture', 448);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (102, 'NDE', 959);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (103, 'Integrated Marketing', 755);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (104, 'TGA', 503);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (105, 'GMDSS', 58);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (106, 'FP-C', 267);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (107, 'Gas Chromatography', 646);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (108, 'SDLX', 548);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (109, 'GMS', 987);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (110, 'NSS', 457);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (111, 'Outdoor Kitchens', 445);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (112, 'Jazz Dance', 232);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (113, 'PDE', 355);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (114, 'Journal Entries', 700);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (115, 'ATG CSC', 983);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (116, 'FBT', 37);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (117, 'Volunteer Management', 31);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (118, 'CMM', 684);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (119, 'Yard Signs', 178);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (120, 'Alternative Energy', 133);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (121, 'IRS problem resolution', 854);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (122, 'SSL Certificates', 936);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (123, 'HTML Help Workshop', 769);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (124, 'Xcart', 560);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (125, 'Production Planning', 83);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (126, 'Online Gaming', 535);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (127, 'MMC', 244);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (128, 'Civil Litigation', 376);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (129, 'Corporate Branding', 986);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (130, 'Web TV', 222);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (131, 'High Rise', 503);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (132, 'IUI', 940);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (133, 'HTA', 63);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (134, 'Gw Basic', 668);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (135, 'NGOs', 716);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (136, 'Xsan', 792);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (137, 'Google Docs', 427);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (138, 'MD&amp;A', 109);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (139, 'Strategy', 928);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (140, 'Commercial Property Owners', 314);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (141, 'High Net Worth Individuals', 696);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (142, 'XLSTAT', 838);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (143, 'Bhangra', 848);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (144, 'Wellness Coaching', 352);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (145, 'Rooms Division', 49);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (146, 'MXG', 550);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (147, 'XRR', 402);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (148, 'Class III Medical Devices', 603);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (149, 'QuickBooks', 531);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (150, 'XPages', 74);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (151, 'LGBT Rights', 629);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (152, 'DLX', 322);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (153, 'Osteoporosis', 913);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (154, 'CCNP Certified', 426);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (155, 'CRM', 557);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (156, 'Pyxis', 836);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (157, 'Lua', 475);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (158, 'Active Directory', 762);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (159, 'HDMI', 931);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (160, 'Machine Tools', 128);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (161, 'WTX', 321);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (162, 'System Testing', 649);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (163, 'RDFS', 301);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (164, 'SDLC', 585);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (165, 'CFDs', 781);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (166, 'Network Architecture', 24);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (167, 'MDF', 835);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (168, 'Cultural Awareness', 207);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (169, 'Typing', 189);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (170, 'TQM', 401);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (171, 'CNN Newsource', 429);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (172, 'NIST', 443);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (173, 'Project Oversight', 153);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (174, 'CFIA', 984);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (175, 'NX-OS', 276);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (176, 'Accounting', 667);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (177, 'Site Planning', 8);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (178, 'MLRO', 870);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (179, 'NREMT', 74);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (180, 'Brokerage', 827);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (181, 'Functional Training', 782);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (182, 'DSLAM', 665);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (183, 'Tomcat', 871);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (184, 'Xajax', 939);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (185, 'TMN', 217);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (186, 'NHS', 320);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (187, 'National Association of Realtors', 927);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (188, 'Pricing', 372);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (189, 'Direct Marketing', 458);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (190, 'SQR', 214);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (191, 'Lutron', 488);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (192, 'PVM', 361);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (193, 'Organizational Behavior', 983);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (194, 'RMP', 43);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (195, 'Juvenile Justice', 637);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (196, 'Network Security', 141);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (197, 'World War II', 343);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (198, 'FTR', 921);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (199, 'SQL Server Management Studio', 376);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (200, 'VM', 656);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (201, 'IOS-XR', 202);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (202, 'Rolling Stock', 83);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (203, 'Awk', 37);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (204, 'Agrochemicals', 148);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (205, 'Hypnosis', 289);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (206, 'MBD', 482);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (207, 'MS Excel Pivot Tables', 668);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (208, 'Tax Law', 759);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (209, 'Investments', 403);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (210, 'IT Recruitment', 469);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (211, 'XPDL', 176);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (212, 'Lyra', 421);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (213, 'IR', 470);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (214, 'zLinux', 348);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (215, 'SMT Kingdom', 468);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (216, 'Vector NTI', 935);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (217, '7 QC Tools', 876);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (218, 'RPM', 524);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (219, 'Organic Chemistry', 804);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (220, 'Listings', 533);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (221, 'Art Direction', 579);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (222, 'KWI', 940);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (223, 'cGMP manufacturing', 90);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (224, 'NTSC', 85);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (225, 'Aquatic Therapy', 378);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (226, 'Educational Technology', 340);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (227, 'NFL', 980);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (228, 'Ableton Live', 277);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (229, 'Soft Skills', 542);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (230, 'Human Rights', 134);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (231, 'Social Psychology', 574);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (232, 'GSM', 243);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (233, 'SAP Business ByDesign', 289);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (234, 'ASP', 997);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (235, 'LS-DYNA', 596);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (236, 'Tortoise CVS', 483);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (237, 'Root Cause Analysis', 221);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (238, 'Nursing Care', 60);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (239, 'Commercial Real Estate', 77);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (240, 'Beverage Industry', 907);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (241, 'Yeast', 102);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (242, 'Agilent ADS', 231);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (243, 'PK/PD', 624);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (244, 'IPv6', 183);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (245, 'Pylons', 110);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (246, 'PMC', 636);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (247, 'TMW', 589);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (248, 'AED', 151);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (249, 'Governmental Affairs', 220);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (250, 'JSON-RPC', 98);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (251, 'Piloting', 63);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (252, 'Skin Care Products', 783);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (253, 'MFC', 504);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (254, 'WDS', 768);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (255, 'Kontakt', 812);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (256, 'CTM', 400);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (257, 'RMF', 772);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (258, 'HtmlUnit', 306);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (259, 'Intercultural Awareness', 731);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (260, 'Pivot Tables', 243);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (261, 'DVB-S2', 407);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (262, 'Get Along Well with Others', 857);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (263, 'Access Control', 707);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (264, 'Axys', 138);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (265, 'RDFa', 179);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (266, 'PyGTK', 398);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (267, 'Phase II Subsurface Investigations', 413);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (268, 'Silhouette FX', 460);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (269, 'MRO Management', 291);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (270, 'DC-9', 520);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (271, 'SRP', 592);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (272, 'Glaucoma', 464);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (273, 'CVaR', 690);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (274, 'DCS', 751);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (275, 'Product Knowledge', 91);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (276, 'Eyelash &amp; Eyebrow Tinting', 448);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (277, 'Pdf', 626);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (278, 'Telecom BSS', 327);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (279, 'GTS', 635);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (280, 'Thermodynamics', 147);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (281, 'LSS', 387);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (282, 'VMware Fusion', 258);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (283, 'SCADA', 508);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (284, 'Export', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (285, 'Workforce Management', 712);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (286, 'HBOC', 900);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (287, 'HW Design', 693);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (288, 'ISO 14001', 213);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (289, 'PDS', 531);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (290, 'HR Information Management', 141);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (291, 'Administrative Law', 265);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (292, 'Windows 7', 219);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (293, 'CICS', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (294, 'Space Planning', 610);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (295, 'Jingles', 410);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (296, 'DFSS', 502);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (297, 'Vlookup', 1000);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (298, 'Gigabit Ethernet', 15);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (299, 'Wholesale Banking', 659);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (300, 'TyMetrix', 906);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (301, 'TMF', 253);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (302, 'MQL4', 50);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (303, 'XFS', 76);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (304, 'DC Drives', 447);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (305, 'Novell', 479);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (306, 'Employee Handbooks', 522);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (307, 'Olefins', 547);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (308, 'Distance Learning', 652);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (309, 'Network Architecture', 835);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (310, 'Leadership', 761);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (311, 'News Writing', 172);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (312, 'Aircraft Systems', 629);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (313, 'Slope Stability Analysis', 564);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (314, 'Tourism Management', 988);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (315, 'DTE', 63);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (316, 'MBTI', 392);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (317, 'BPA', 241);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (318, 'Japanese Language Proficiency Test', 766);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (319, 'Dysarthria', 583);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (320, 'External Audit', 279);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (321, 'MLP', 111);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (322, 'Genomics', 487);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (323, 'Zynx', 765);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (324, 'Up-selling', 76);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (325, 'TM1', 612);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (326, 'Hydraulic Systems', 507);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (327, 'Claims Management', 46);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (328, 'UCC filings', 882);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (329, 'Test Driven Development', 88);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (330, 'Animal Work', 684);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (331, 'Yoga', 581);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (332, 'Wellness Coaching', 499);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (333, 'Platform LSF', 607);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (334, 'MPE', 372);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (335, 'FM200', 412);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (336, 'Direct Marketing', 715);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (337, 'Online Lead Generation', 530);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (338, 'Industrial Ethernet', 234);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (339, 'RSpec', 81);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (340, 'FME', 390);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (341, 'Managed Services', 135);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (342, 'Fraud', 606);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (343, 'IVA', 466);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (344, 'UHV', 146);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (345, 'ICD-10', 345);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (346, 'Embedded Systems', 917);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (347, 'FpML', 209);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (348, 'HSEEP', 651);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (349, 'Interactive Whiteboard', 505);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (350, 'Turbomachinery', 743);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (351, 'FX Hedging', 724);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (352, 'OEL', 619);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (353, 'Ghostwriting', 821);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (354, 'TPP', 810);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (355, 'FGD', 397);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (356, 'Overcome Objections', 884);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (357, 'Applied Behavior Analysis', 342);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (358, 'Analysis', 108);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (359, 'Classical Guitar', 272);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (360, 'Software Documentation', 603);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (361, 'Knowledge Representation', 721);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (362, 'Xpediter', 71);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (363, 'Sketching', 571);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (364, 'RCP', 338);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (365, 'Electrical Controls', 348);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (366, 'Abstraction', 311);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (367, 'PPBES', 30);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (368, 'ADP Payroll', 460);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (369, 'TPC', 179);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (370, 'Nitrous Oxide', 777);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (371, 'CP', 596);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (372, 'Xpediter', 465);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (373, 'DCL', 629);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (374, 'WFA', 774);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (375, 'Student Financial Aid', 481);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (376, 'Home Staging', 319);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (377, 'jQuery', 488);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (378, 'Change Management', 459);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (379, 'Sales Management', 959);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (380, 'JSR 168', 883);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (381, 'Automobile', 770);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (382, 'Unicenter TNG', 40);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (383, 'Business Transformation', 710);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (384, 'Overcome Objections', 867);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (385, 'Lyophilization', 73);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (386, 'RFP Generation', 615);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (387, 'TFM', 907);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (388, 'Process Efficiency', 642);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (389, 'Honeywell DCS', 836);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (390, 'LDRPS', 810);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (391, 'IRS problem resolution', 279);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (392, 'OSGi', 894);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (393, 'FHLMC', 750);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (394, 'WSDL', 2);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (395, 'Electronic Payments', 628);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (396, 'RCM', 192);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (397, 'Mechanical Engineering', 148);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (398, 'Smartstream TLM', 852);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (399, 'Equity Valuation', 776);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (400, 'Unreal Engine 3', 682);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (401, 'Journalism', 50);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (402, 'Alcoholic Beverages', 778);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (403, 'Beer', 857);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (404, 'BGP', 344);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (405, 'CNS disorders', 737);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (406, 'Mental Health', 156);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (407, 'ISM', 793);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (408, 'Bodywork', 831);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (409, 'Financial Reporting', 321);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (410, 'Critical Care', 560);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (411, 'Google Adwords', 17);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (412, 'ISDN', 797);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (413, 'EBA', 33);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (414, 'XP/Vista/7', 188);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (415, 'Banking', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (416, 'Social Justice', 54);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (417, 'FMA', 992);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (418, 'Nuclear', 822);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (419, 'NSIS', 853);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (420, 'Distribution Center Operations', 192);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (421, 'SDH', 283);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (422, 'Java Enterprise Edition', 939);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (423, 'Kronos', 404);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (424, 'NSI', 325);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (425, 'Wills', 830);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (426, 'GDI+', 677);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (427, 'Operational Due Diligence', 275);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (428, 'Strategic Partnerships', 843);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (429, 'QRC', 975);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (430, 'Zuken', 838);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (431, 'MDR', 267);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (432, 'TVCs', 256);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (433, 'TK Solver', 353);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (434, 'Transitional Justice', 924);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (435, 'Chromatography', 565);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (436, 'FDA GMP', 924);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (437, 'Non-profit Volunteering', 922);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (438, 'ODM management', 357);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (439, 'DSP BIOS', 163);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (440, 'Tax Advisory', 788);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (441, 'Cloud Computing', 284);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (442, 'CPFR', 895);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (443, 'Overseeing Projects', 194);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (444, 'Phase II Subsurface Investigations', 441);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (445, 'Universal Life', 984);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (446, 'PKCS', 138);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (447, 'OAT', 13);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (448, 'LLP', 730);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (449, 'Animal Behavior', 141);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (450, 'Business Process', 568);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (451, 'Aerodynamics', 873);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (452, 'BSCI', 788);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (453, 'Appointment Scheduling', 617);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (454, 'Family Medicine', 199);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (455, 'Nightlife', 712);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (456, 'Urban Studies', 321);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (457, 'NDF', 493);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (458, 'XUL', 193);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (459, 'EWM', 45);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (460, 'Equestrian', 384);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (461, 'CGEIT', 943);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (462, 'Feature Articles', 918);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (463, 'Video Games', 20);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (464, 'Veneers', 456);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (465, 'RMAN', 103);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (466, 'vCloud', 538);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (467, 'Turbo Pascal', 195);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (468, 'PQQ', 558);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (469, 'Ethics', 163);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (470, 'Hg', 245);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (471, 'Molecular Cloning', 510);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (472, 'MM modules', 545);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (473, 'BCLS', 103);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (474, 'RCA', 575);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (475, 'Benefits Administration', 273);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (476, 'Analytical Ultracentrifugation', 959);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (477, 'Website Development', 278);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (478, 'Weddings', 149);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (479, 'Healthcare Consulting', 421);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (480, 'MLA Style', 547);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (481, 'Hydrography', 510);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (482, 'UIX', 253);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (483, 'VCM', 219);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (484, 'Turbo C++', 625);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (485, 'DB2', 139);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (486, 'GPS Applications', 919);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (487, 'Wellness', 447);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (488, 'Pharmacy Benefit Management', 868);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (489, 'Turbo Pascal', 475);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (490, 'Handmade Jewelry', 896);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (491, 'Snorkeling', 61);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (492, 'NHL', 105);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (493, 'Financial Reporting', 971);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (494, 'QS9000', 922);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (495, 'User Scenarios', 688);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (496, 'Luxury Goods', 392);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (497, 'CDO', 12);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (498, 'Lynx', 15);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (499, 'Human Resources', 36);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (500, 'JES2', 162);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (501, 'Tax Preparation', 669);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (502, 'Wireless Networking', 121);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (503, 'TCR', 507);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (504, 'Change Orders', 53);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (505, 'Ethical Decision Making', 840);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (506, 'Multilingual', 612);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (507, 'NDS', 593);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (508, 'GS1', 476);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (509, 'Marketing', 877);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (510, 'Evidence', 5);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (511, 'Oracle VM', 6);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (512, 'Xerces', 181);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (513, 'International Humanitarian Law', 227);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (514, 'Team Mgmt', 420);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (515, 'Play-by-play', 830);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (516, 'NPL', 732);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (517, 'Portrait Photography', 907);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (518, 'Hazardous Waste Management', 968);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (519, 'NDT', 592);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (520, 'QMF', 866);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (521, 'MICROS', 980);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (522, 'Seismic Attributes', 741);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (523, 'Surgery', 59);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (524, 'TMDLs', 543);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (525, 'Audio Editing', 50);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (526, 'HSEEP', 153);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (527, 'Cash Flow Forecasting', 752);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (528, 'Numerical Ability', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (529, 'Risk Analysis', 450);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (530, 'GNU/Linux', 690);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (531, 'Lytec', 856);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (532, 'UVLayout', 466);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (533, 'Patents', 792);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (534, 'MXP', 628);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (535, 'CDS', 681);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (536, 'SSH Client', 901);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (537, 'GXT', 534);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (538, 'NCFM Certified', 259);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (539, 'NCMR', 103);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (540, 'Trading', 495);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (541, 'Data Quality', 600);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (542, 'RVs', 347);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (543, 'jQuery UI', 640);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (544, 'IFTA', 620);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (545, 'UDF', 838);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (546, 'Internet Banking', 157);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (547, 'VSP 4', 625);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (548, 'LWD', 615);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (549, 'Aerospace Structures', 608);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (550, 'Youth Work', 683);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (551, 'VMM', 709);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (552, 'Offshore Drilling', 201);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (553, 'FSL', 57);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (554, 'Kyoto Protocol', 408);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (555, 'Cisco VoIP', 463);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (556, 'Product Development', 411);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (557, 'Property &amp; Casualty Insurance', 509);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (558, 'AHP', 735);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (559, 'cXML', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (560, 'Kinetic Typography', 471);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (561, 'WordPerfect', 422);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (562, 'Turkish', 484);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (563, 'Corporate Identity', 495);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (564, 'DNS Administration', 908);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (565, 'Church Events', 760);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (566, 'VTK', 754);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (567, 'Start-up Environment', 127);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (568, 'FDD', 664);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (569, 'DHCPv6', 37);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (570, 'PQRI', 365);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (571, 'EMS', 618);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (572, 'YAML', 261);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (573, 'Blood Pressure', 944);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (574, 'PVC', 167);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (575, 'MRV', 800);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (576, 'VPN', 19);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (577, 'Smart Cards', 117);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (578, 'TCR', 717);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (579, 'Ion Chromatography', 280);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (580, 'WTT', 497);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (581, 'DTMF', 540);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (582, 'Jetty', 232);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (583, 'Psychopharmacology', 661);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (584, 'Organizational Behavior', 888);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (585, 'Failure Analysis', 55);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (586, 'LBO', 935);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (587, 'Legal Advice', 33);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (588, 'RVM', 386);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (589, 'VLS', 916);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (590, 'Trade Marketing', 144);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (591, 'LaTeX', 606);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (592, 'RRDTool', 343);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (593, 'Company Set-up', 137);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (594, 'HDL Designer', 160);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (595, 'JNA', 449);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (596, 'Sustainable Agriculture', 496);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (597, 'JDE One World', 295);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (598, 'FSC certified', 81);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (599, 'Women Owned Business', 968);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (600, 'WM modules', 902);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (601, 'Win CVS', 495);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (602, 'Powers of Attorney', 413);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (603, 'JTAG', 437);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (604, 'Image Processing', 326);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (605, 'GCPs', 238);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (606, 'eEye Retina', 261);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (607, 'KPI Reports', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (608, 'PDP', 933);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (609, 'Enterprise Architecture', 463);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (610, 'Oxidative Stress', 774);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (611, 'Factory', 309);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (612, 'CQS', 790);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (613, 'NCMR', 326);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (614, 'Packaging', 347);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (615, 'OAS', 407);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (616, 'GML', 321);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (617, 'DNV', 691);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (618, 'Internal Audit', 531);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (619, 'Tcpdump', 544);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (620, 'BMP', 404);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (621, 'Dogs', 222);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (622, 'IGMP Snooping', 902);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (623, 'IBM AS/400', 661);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (624, 'Benefits Administration', 780);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (625, 'LEED AP', 788);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (626, 'IAD', 275);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (627, 'Odeon', 106);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (628, 'HCFA', 630);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (629, 'Business Efficiency', 819);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (630, 'Oxygen', 698);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (631, 'Patents', 834);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (632, 'ATP', 584);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (633, 'WBS', 255);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (634, 'MD-11', 921);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (635, 'HDL Designer', 631);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (636, 'International HR', 571);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (637, 'Oracle ERP', 453);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (638, 'Adolescents', 236);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (639, 'VA Loans', 35);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (640, 'Water', 609);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (641, 'UAT Coordination', 205);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (642, 'Visual Identity', 503);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (643, 'Materials Science', 16);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (644, 'Patrol', 418);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (645, 'Awareness Raising', 623);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (646, 'IAM', 563);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (647, 'Flight Test', 381);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (648, 'XUL', 536);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (649, 'Copy Typing', 898);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (650, 'NVQs', 250);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (651, 'Outplacement', 777);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (652, 'SMT Kingdom', 675);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (653, 'Knowledge Sharing', 252);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (654, 'Crystal Xcelsius', 868);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (655, 'Fine Art Photography', 949);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (656, 'Football', 84);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (657, 'UDS', 369);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (658, 'iOS', 409);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (659, 'SQL Azure', 112);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (660, 'VMS', 846);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (661, 'CVE', 89);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (662, 'Youth Marketing', 334);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (663, 'GLP', 416);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (664, 'Egyptology', 724);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (665, 'SAP PP', 998);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (666, 'BTE', 390);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (667, 'Income Tax', 750);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (668, 'Microsoft Dynamics GP', 795);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (669, 'HTFS', 158);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (670, 'Affordable Housing', 226);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (671, 'OB/GYN', 70);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (672, 'EGL', 189);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (673, 'Underscore.js', 303);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (674, 'Qbasic', 438);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (675, 'AHLTA', 199);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (676, 'LS9', 436);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (677, 'DMR', 307);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (678, 'Recombinant DNA', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (679, 'ODE', 998);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (680, 'CSPro', 352);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (681, 'Hummingbird DM', 637);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (682, 'Skin Care Products', 199);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (683, 'IKEv2', 967);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (684, 'vRanger', 254);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (685, 'Financial Risk Management', 943);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (686, 'Tiles', 780);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (687, 'MPE', 990);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (688, 'TBB', 797);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (689, 'Music Publishing', 218);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (690, 'Commercial Litigation', 260);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (691, 'Google Earth', 862);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (692, 'Workshops', 100);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (693, 'Electric Utility', 996);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (694, 'Classical', 817);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (695, 'MRI Software', 107);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (696, 'TFS', 948);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (697, 'Healing', 681);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (698, 'PBIS', 924);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (699, 'UCC filings', 864);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (700, 'Tunnels', 49);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (701, 'XACT', 445);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (702, 'MicroStation', 520);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (703, 'PMO Services', 622);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (704, 'CNC Mill', 815);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (705, 'Glasses', 781);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (706, 'Big Data', 433);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (707, 'Microsoft Dynamics AX', 316);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (708, 'HDRI', 293);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (709, 'International Economics', 804);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (710, 'Practice CS', 445);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (711, 'WSRR', 813);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (712, 'Client Services', 419);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (713, 'Beer', 976);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (714, 'UCINET', 704);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (715, 'CPCU', 744);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (716, 'European Union Politics', 14);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (717, 'Gaming Industry', 328);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (718, 'CTC', 548);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (719, 'RAN', 61);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (720, 'Radio', 532);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (721, 'e-QIP', 343);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (722, 'Uzbek', 82);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (723, 'UK Employment Law', 611);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (724, 'Valves', 689);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (725, 'HSEEP', 359);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (726, 'PWB', 424);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (727, 'CSI', 942);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (728, 'IB', 733);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (729, 'BLS', 997);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (730, 'Field Work', 807);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (731, 'Functional Specifications', 786);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (732, 'PFP', 615);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (733, 'Gnuplot', 761);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (734, 'Jet Ski', 769);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (735, 'Geography', 20);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (736, 'Beauty Industry', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (737, 'NVQs', 989);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (738, 'XFire', 825);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (739, 'Zone Alarm', 908);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (740, 'Weapons of Mass Destruction', 792);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (741, 'WBEM', 167);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (742, 'Organizational Design', 710);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (743, 'MLA', 621);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (744, 'LPIC', 482);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (745, 'GCPs', 540);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (746, 'Psychological Assessment', 968);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (747, 'Claims Management', 634);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (748, 'Agents', 124);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (749, 'Flex', 271);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (750, 'VPN', 792);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (751, 'FrameMaker', 928);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (752, 'Brokerage', 982);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (753, 'CDMA', 648);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (754, 'JRockit', 152);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (755, 'Microsoft Dynamics GP', 610);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (756, 'BPF', 146);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (757, 'ABR', 570);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (758, 'LLVM', 63);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (759, 'TV series', 598);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (760, 'Osteoporosis', 25);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (761, 'NCIC', 385);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (762, 'Healthcare Information Technology', 993);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (763, 'Unix', 983);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (764, 'Offshoring', 208);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (765, 'KDE', 372);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (766, 'Quantitative Finance', 634);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (767, 'Epicor', 802);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (768, 'Painting', 597);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (769, 'ICD-10', 231);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (770, 'GPS Applications', 961);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (771, 'HSI', 578);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (772, 'RT-PCR', 449);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (773, 'Air Force', 583);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (774, 'Tour Operators', 420);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (775, 'Rheumatology', 329);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (776, 'VMI', 674);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (777, 'JCAHO', 24);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (778, 'Venue Management', 243);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (779, 'EIP', 744);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (780, 'RS422', 998);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (781, 'Owner Representation', 560);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (782, 'Airline Ticketing', 817);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (783, 'Orthopedics', 661);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (784, 'Aerospace', 453);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (785, 'IBM AIX', 625);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (786, 'HCP', 1000);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (787, 'WTO', 822);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (788, 'Ericsson OSS', 775);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (789, 'Emergency Management', 247);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (790, 'Financial Accounting', 259);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (791, 'GSS', 967);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (792, 'CDL', 21);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (793, 'ProSystem fx Engagement', 468);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (794, 'Business Valuation', 209);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (795, 'IT Risk Management', 591);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (796, 'MHP', 968);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (797, 'DDI', 989);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (798, 'Substance Abuse Prevention', 708);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (799, 'RPG III', 690);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (800, 'QSAR', 344);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (801, 'Acute Care', 365);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (802, 'Trading Systems', 781);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (803, 'Xenu', 495);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (804, 'CDM', 421);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (805, 'Annual Giving', 712);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (806, 'Attendance Management', 751);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (807, 'Fertilizers', 764);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (808, 'MS-DOS', 887);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (809, 'Zuken', 86);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (810, 'Hand Knitting', 884);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (811, 'HP Openview', 185);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (812, 'RFI', 42);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (813, 'VC-1', 947);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (814, 'International Shipping', 407);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (815, 'XML Publisher', 306);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (816, 'MLB', 704);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (817, 'SAP-SD', 859);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (818, 'DWBI', 471);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (819, 'Test Equipment', 874);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (820, 'qRT-PCR', 114);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (821, 'HBase', 225);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (822, 'Bluetooth', 144);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (823, 'Avid Xpress', 444);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (824, 'Gym', 540);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (825, 'Content Strategy', 591);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (826, 'OATS', 96);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (827, 'NDF', 596);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (828, 'DHCP', 612);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (829, 'New Media', 7);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (830, 'System Testing', 207);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (831, 'Payroll', 585);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (832, 'Customer Acquisition', 136);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (833, 'Government Contracting', 119);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (834, 'RF', 818);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (835, 'Outerwear', 650);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (836, 'Cash Handling', 226);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (837, 'SAP MDM', 588);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (838, 'Mortgage Underwriting', 655);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (839, 'Footwear', 650);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (840, 'IUI', 695);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (841, 'BS7799', 857);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (842, 'Xoops', 926);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (843, 'Keratin Treatment', 817);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (844, 'RCSA', 727);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (845, 'VDSL', 424);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (846, 'HP uCMDB', 912);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (847, 'JCreator', 108);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (848, 'Threat &amp; Vulnerability Management', 225);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (849, 'McAfee', 165);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (850, 'qRT-PCR', 447);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (851, 'Information Security Awareness', 314);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (852, 'Zyxel', 638);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (853, 'Juniper Switches', 891);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (854, 'Land Use Planning', 458);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (855, 'SQL Azure', 872);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (856, 'Constructive Feedback', 927);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (857, 'HTML Scripting', 904);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (858, 'HV', 436);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (859, 'BMI', 782);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (860, 'POS', 944);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (861, 'Dogs', 612);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (862, 'UC4', 950);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (863, 'Board Certified', 548);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (864, 'Nanoparticles', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (865, 'Project Engineering', 115);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (866, 'Website Updating', 725);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (867, 'MyEclipse', 104);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (868, 'Underscore.js', 162);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (869, 'MBR', 673);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (870, 'DDI Certified Facilitator', 685);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (871, 'Active TS/SCI Clearance', 219);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (872, 'UAT Coordination', 291);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (873, 'VTAM', 838);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (874, 'ISO 13485', 129);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (875, 'TDC3000', 180);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (876, 'Virtualization', 933);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (877, 'HR Information Management', 42);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (878, 'ICDL', 425);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (879, 'Financial Reporting', 218);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (880, 'Key Performance Indicators', 689);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (881, 'Business Rules', 462);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (882, 'Financial Risk', 108);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (883, 'FP7', 118);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (884, 'QRC', 675);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (885, 'Holistic Health', 831);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (886, 'Fraud Detection', 537);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (887, 'Node.js', 291);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (888, 'RTO', 271);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (889, 'SFR Certified', 967);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (890, 'Nielsen', 925);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (891, 'Oleochemicals', 232);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (892, 'Siebel', 596);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (893, 'MHE', 21);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (894, 'RFQ', 633);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (895, 'Omega', 703);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (896, 'Norton Ghost', 854);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (897, 'SSCP', 387);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (898, 'Vacation Homes', 311);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (899, 'IATA', 869);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (900, 'PFI', 732);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (901, 'Logo Design', 171);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (902, 'Drafting Agreements', 886);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (903, 'IT Service Management', 551);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (904, 'Front-end', 732);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (905, 'Drawing', 319);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (906, 'PMCS', 60);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (907, 'LSF', 932);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (908, 'Surveillance', 347);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (909, 'Computer Network Operations', 899);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (910, 'SQL Loader', 542);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (911, 'Pygame', 690);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (912, 'OllyDbg', 881);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (913, 'XRR', 841);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (914, 'QLab', 254);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (915, 'JDK', 287);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (916, 'jQTouch', 299);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (917, 'MIS', 637);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (918, 'Art History', 745);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (919, 'Omnet++', 899);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (920, 'Glasses', 50);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (921, 'SharePoint', 412);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (922, 'Laboratory', 71);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (923, 'Sheet Metal', 74);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (924, 'Failure Analysis', 766);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (925, 'Global Marketing', 760);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (926, 'OHS', 778);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (927, 'GC-MS', 232);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (928, 'OSHA', 205);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (929, 'MVT', 631);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (930, 'JDeveloper', 679);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (931, 'Literature', 402);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (932, 'Sales Management', 750);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (933, 'Shopping Centers', 75);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (934, 'Gas', 70);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (935, 'LTD', 696);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (936, 'Vsftpd', 159);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (937, 'Customer Follow-up', 174);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (938, 'MD5', 803);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (939, 'UV', 375);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (940, 'DG Sets', 700);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (941, 'Outcomes Research', 326);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (942, 'High Availability', 678);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (943, 'IEEE standards', 770);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (944, 'Metro Ethernet', 812);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (945, 'Breaking News', 214);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (946, 'XRR', 666);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (947, 'LCR', 247);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (948, 'Strategy', 794);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (949, 'Quantitative Research', 820);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (950, 'Active DoD Secret Clearance', 430);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (951, 'BMR', 639);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (952, 'Keynote', 744);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (953, 'Sports Management', 371);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (954, 'GTD', 204);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (955, 'Autism Spectrum Disorders', 895);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (956, 'TMJ Treatment', 415);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (957, 'Logic Pro', 869);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (958, 'Pediatrics', 160);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (959, 'PIM-DM', 974);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (960, 'NTFS', 831);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (961, 'Analog Circuit Design', 444);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (962, 'JAX-WS', 74);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (963, 'Niche Marketing', 158);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (964, 'AOI', 696);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (965, 'Euthanasia', 605);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (966, 'RPG Free', 535);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (967, 'Historical Research', 181);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (968, 'GWAPT', 14);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (969, 'Museums', 13);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (970, 'RDz', 394);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (971, 'PCR Primer Design', 277);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (972, '360 Feedback', 960);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (973, 'MDS', 392);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (974, 'Numerical Simulation', 522);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (975, 'GAAP', 836);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (976, 'CT Summation', 367);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (977, 'Data Entry', 930);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (978, 'Errors &amp; Omissions', 603);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (979, 'YUI', 205);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (980, 'IT Operations', 591);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (981, 'DBC', 114);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (982, 'Higher Education Administration', 67);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (983, 'DUI Defense', 626);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (984, 'Powers of Attorney', 26);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (985, '.htaccess', 46);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (986, 'Unit Testing', 786);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (987, 'IVD', 664);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (988, 'National Association of Realtors', 750);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (989, 'Ab Initio', 567);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (990, 'Algorithms', 308);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (991, 'Logistics Management', 745);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (992, 'Air Freight', 506);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (993, 'Hotels', 966);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (994, 'SVT', 814);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (995, 'vCloud', 99);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (996, 'Naval Architecture', 71);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (997, 'NRC', 455);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (998, 'xPON', 752);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (999, 'Rhinoceros', 984);
insert into LOGROS_ENTITY (id, descripcion, jugador_id) values (1000, 'TTP', 775);
